name : build html image and deploy to ec2
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-image-react:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Added details to image
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{vars.DOCKER_USERNAME}}/${{secrets.IMAGE_NAME}}
          tags: |
            latest
            v1.0.${{github.run_number}}
        run: |
          echo "Image name: ${{vars.DOCKER_USERNAME}}/${{secrets.IMAGE_NAME}}"
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{vars.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Print image metadata
        run: |
          echo "docker username"
          echo "${{vars.DOCKER_USERNAME}}"
          echo "image name"
          echo "${{secrets.IMAGE_NAME}}"
          echo "tags"
          echo "${{steps.meta.outputs.tags}}"

        
        